/* ==========================================================================
   MADEEA — productos.js
   Arreglo de referencias del catálogo de molduras.
   Generado a partir del catálogo oficial MADEEA (2026).
   Cada producto: ref, img, categoria, ancho, espesor (o diametro para perfiles redondos).
   ========================================================================== */

const productos = [
  { ref: "101", categoria: "Guardaluces", imagen: "assets/molduras/101.jpg", ancho: "5 cm", espesor: "0.8 cm" },
  { ref: "102", categoria: "Guardaluces", imagen: "assets/molduras/102.jpg", ancho: "4 cm", espesor: "0.6 cm" },
  { ref: "103", categoria: "Guardaluces", imagen: "assets/molduras/103.jpg", ancho: "4 cm", espesor: "0.8 cm" },
  { ref: "104", categoria: "Guardaluces", imagen: "assets/molduras/104.jpg", ancho: "4 cm", espesor: "0.7 cm" },
  { ref: "104p", categoria: "Guardaluces", imagen: "assets/molduras/104p.jpg", ancho: "3 cm", espesor: "0.6 cm" },
  { ref: "106", categoria: "Guardaluces", imagen: "assets/molduras/106.jpg", ancho: "4 cm", espesor: "0.7 cm" },
  { ref: "107", categoria: "Guardaluces", imagen: "assets/molduras/107.jpg", ancho: "3 cm", espesor: "0.7 cm" },
  { ref: "107a", categoria: "Guardaluces", imagen: "assets/molduras/107a.jpg", ancho: "3 cm", espesor: "0.8 cm" },
  { ref: "108", categoria: "Guardaluces", imagen: "assets/molduras/108.jpg", ancho: "2 cm", espesor: "0.6 cm" },
  { ref: "109", categoria: "Guardaluces", imagen: "assets/molduras/109.jpg", ancho: "5 cm", espesor: "0.8 cm" },
  { ref: "110", categoria: "Guardaluces", imagen: "assets/molduras/110.jpg", ancho: "5 cm", espesor: "1.5 cm" },
  { ref: "118", categoria: "Guardaluces", imagen: "assets/molduras/118.jpg", ancho: "4 cm", espesor: "1.2 cm" },
  { ref: "122", categoria: "Guardaluces", imagen: "assets/molduras/122.jpg", ancho: "2 cm", espesor: "0.8 cm" },
  { ref: "123", categoria: "Guardaluces", imagen: "assets/molduras/123.jpg", ancho: "2 cm", espesor: "0.8 cm" },
  { ref: "329", categoria: "Guardaluces", imagen: "assets/molduras/329.jpg", ancho: "2 cm", espesor: "0.8 cm" },
  { ref: "329a", categoria: "Guardaluces", imagen: "assets/molduras/329a.jpg", ancho: "4 cm", espesor: "1.2 cm" },
  { ref: "402", categoria: "Guardaluces", imagen: "assets/molduras/402.jpg", ancho: "5 cm", espesor: "0.9 cm" },
  { ref: "410", categoria: "Guardaluces", imagen: "assets/molduras/410.jpg", ancho: "2 cm", espesor: "0.8 cm" },
  { ref: "414e", categoria: "Guardaluces", imagen: "assets/molduras/414e.jpg", ancho: "4 cm", espesor: "0.7 cm" },
  { ref: "416", categoria: "Guardaluces", imagen: "assets/molduras/416.jpg", ancho: "3 cm", espesor: "0.8 cm" },
  { ref: "417", categoria: "Guardaluces", imagen: "assets/molduras/417.jpg", ancho: "5 cm", espesor: "0.8 cm" },
  { ref: "513", categoria: "Guardaluces", imagen: "assets/molduras/513.jpg", ancho: "2.5 cm", espesor: "0.6 cm" },
  { ref: "2x0.6", categoria: "Guardaluces", imagen: "assets/molduras/2x0.6.jpg", ancho: "2 cm", espesor: "0.6 cm" },
  { ref: "3x0.6", categoria: "Guardaluces", imagen: "assets/molduras/3x0.6.jpg", ancho: "3 cm", espesor: "0.6 cm" },
  { ref: "4x0.6", categoria: "Guardaluces", imagen: "assets/molduras/4x0.6.jpg", ancho: "4 cm", espesor: "0.6 cm" },
  { ref: "209", categoria: "Esquineros", imagen: "assets/molduras/209.jpg", ancho: "3 cm", espesor: "3 cm" },
  { ref: "210", categoria: "Esquineros", imagen: "assets/molduras/210.jpg", ancho: "3.6 cm", espesor: "2.5 cm" },
  { ref: "211", categoria: "Esquineros", imagen: "assets/molduras/211.jpg", ancho: "4 cm", espesor: "2.5 cm" },
  { ref: "212", categoria: "Esquineros", imagen: "assets/molduras/212.jpg", ancho: "2.5 cm", espesor: "2 cm" },
  { ref: "315", categoria: "Esquineros", imagen: "assets/molduras/315.jpg", ancho: "4 cm", espesor: "2.5 cm" },
  { ref: "504", categoria: "Esquineros", imagen: "assets/molduras/504.jpg", ancho: "3 cm", espesor: "2 cm" },
  { ref: "071 Lazo", categoria: "Complementos", imagen: "assets/molduras/071-lazo.jpg", ancho: "2 cm", espesor: "1.2 cm" },
  { ref: "071 PH", categoria: "Complementos", imagen: "assets/molduras/071-ph.jpg", ancho: "2 cm", espesor: "1 cm" },
  { ref: "071 PV", categoria: "Complementos", imagen: "assets/molduras/071-pv.jpg", ancho: "2 cm", espesor: "0.5 cm" },
  { ref: "409", categoria: "Complementos", imagen: "assets/molduras/409.jpg", ancho: "2.5 cm", espesor: "1 cm" },
  { ref: "412", categoria: "Complementos", imagen: "assets/molduras/412.jpg", ancho: "1 cm", espesor: "0.5 cm" },
  { ref: "510", categoria: "Complementos", imagen: "assets/molduras/510.jpg", ancho: "1.5 cm", espesor: "0.5 cm" },
  { ref: "Complemento #4", categoria: "Complementos", imagen: "assets/molduras/complemento-4.jpg", ancho: "3 cm", espesor: "1.4 cm" },
  { ref: "208", categoria: "Media Caña", imagen: "assets/molduras/208.jpg", ancho: "2.8 cm", espesor: "1.5 cm" },
  { ref: "208 sin filo", categoria: "Media Caña", imagen: "assets/molduras/208-sf.jpg", ancho: "3 cm", espesor: "1 cm" },
  { ref: "208A", categoria: "Media Caña", imagen: "assets/molduras/208a.jpg", ancho: "2.8 cm", espesor: "1.5 cm" },
  { ref: "208A sin filo", categoria: "Media Caña", imagen: "assets/molduras/208a-sf.jpg", ancho: "3 cm", espesor: "1 cm" },
  { ref: "302", categoria: "Media Caña", imagen: "assets/molduras/302.jpg", ancho: "5 cm", espesor: "2 cm" },
  { ref: "302 D", categoria: "Media Caña", imagen: "assets/molduras/302d.jpg", ancho: "4 cm", espesor: "1.5 cm" },
  { ref: "303", categoria: "Media Caña", imagen: "assets/molduras/303.jpg", ancho: "4 cm", espesor: "1.7 cm" },
  { ref: "304", categoria: "Media Caña", imagen: "assets/molduras/304.jpg", ancho: "4 cm", espesor: "2.8 cm" },
  { ref: "305", categoria: "Media Caña", imagen: "assets/molduras/305.jpg", ancho: "5 cm", espesor: "2.5 cm" },
  { ref: "305 sin filo", categoria: "Media Caña", imagen: "assets/molduras/305-sf.jpg", ancho: "5 cm", espesor: "2 cm" },
  { ref: "218", categoria: "Cuarto Bocel", imagen: "assets/molduras/218.jpg", ancho: "1.5 cm", espesor: "1.5 cm" },
  { ref: "322", categoria: "Cuarto Bocel", imagen: "assets/molduras/322.jpg", ancho: "2 cm", espesor: "2 cm" },
  { ref: "323", categoria: "Cuarto Bocel", imagen: "assets/molduras/323.jpg", ancho: "1 cm", espesor: "1 cm" },
  { ref: "408", categoria: "Cuarto Bocel", imagen: "assets/molduras/408.jpg", ancho: "1.2 cm", espesor: "1.2 cm" },
  { ref: "503", categoria: "Cuarto Bocel", imagen: "assets/molduras/503.jpg", ancho: "2.5 cm", espesor: "2.5 cm" },
  { ref: "217", categoria: "Medio Bocel", imagen: "assets/molduras/217.jpg", ancho: "3 cm", espesor: "1.2 cm" },
  { ref: "221", categoria: "Medio Bocel", imagen: "assets/molduras/221.jpg", ancho: "1 cm", espesor: "0.5 cm" },
  { ref: "312", categoria: "Medio Bocel", imagen: "assets/molduras/312.jpg", ancho: "2 cm", espesor: "1 cm" },
  { ref: "319", categoria: "Medio Bocel", imagen: "assets/molduras/319.jpg", ancho: "2.5 cm", espesor: "1.2 cm" },
  { ref: "321", categoria: "Medio Bocel", imagen: "assets/molduras/321.jpg", ancho: "4 cm", espesor: "1.7 cm" },
  { ref: "327", categoria: "Medio Bocel", imagen: "assets/molduras/327.jpg", ancho: "1.2 cm", espesor: "0.8 cm" },
  { ref: "411", categoria: "Medio Bocel", imagen: "assets/molduras/411.jpg", ancho: "1.5 cm", espesor: "0.8 cm" },
  { ref: "216", categoria: "Bolillos", imagen: "assets/molduras/216.jpg", diametro: "1¼\"" },
  { ref: "216p", categoria: "Bolillos", imagen: "assets/molduras/216p.jpg", diametro: "1¼\"" },
  { ref: "219", categoria: "Bolillos", imagen: "assets/molduras/219.jpg", diametro: "½\"" },
  { ref: "220", categoria: "Bolillos", imagen: "assets/molduras/220.jpg", diametro: "⅜\"" },
  { ref: "220A", categoria: "Bolillos", imagen: "assets/molduras/220a.jpg", diametro: "¼\"" },
  { ref: "311", categoria: "Bolillos", imagen: "assets/molduras/311.jpg", diametro: "¾\"" },
  { ref: "320", categoria: "Bolillos", imagen: "assets/molduras/320.jpg", diametro: "⅝\"" },
  { ref: "406", categoria: "Bolillos", imagen: "assets/molduras/406.jpg", diametro: "1½\"" },
  { ref: "406p", categoria: "Bolillos", imagen: "assets/molduras/406p.jpg", diametro: "1½\"" },
  { ref: "407", categoria: "Bolillos", imagen: "assets/molduras/407.jpg", diametro: "1\"" },
  { ref: "407p", categoria: "Bolillos", imagen: "assets/molduras/407p.jpg", diametro: "1\"" },
  { ref: "501", categoria: "Bolillos", imagen: "assets/molduras/501.jpg", diametro: "2\"" },
  { ref: "501p", categoria: "Bolillos", imagen: "assets/molduras/501p.jpg", diametro: "2\"" },
  { ref: "201 (8cm)", categoria: "Zócalos", imagen: "assets/molduras/201-8.jpg", ancho: "8 cm", espesor: "1 cm" },
  { ref: "201 (9cm)", categoria: "Zócalos", imagen: "assets/molduras/201-9.jpg", ancho: "9 cm", espesor: "1 cm" },
  { ref: "202 (8cm)", categoria: "Zócalos", imagen: "assets/molduras/202-8.jpg", ancho: "8 cm", espesor: "1 cm" },
  { ref: "202 (9cm)", categoria: "Zócalos", imagen: "assets/molduras/202-9.jpg", ancho: "9 cm", espesor: "1 cm" },
  { ref: "203 (8cm)", categoria: "Zócalos", imagen: "assets/molduras/203-8.jpg", ancho: "8 cm", espesor: "1 cm" },
  { ref: "203 (9cm)", categoria: "Zócalos", imagen: "assets/molduras/203-9.jpg", ancho: "9 cm", espesor: "1 cm" },
  { ref: "204", categoria: "Zócalos", imagen: "assets/molduras/204.jpg", ancho: "7 cm", espesor: "1 cm" },
  { ref: "205", categoria: "Zócalos", imagen: "assets/molduras/205.jpg", ancho: "7 cm", espesor: "1 cm" },
  { ref: "206", categoria: "Zócalos", imagen: "assets/molduras/206.jpg", ancho: "7 cm", espesor: "1 cm" },
  { ref: "116", categoria: "Soluciones decorativas", imagen: "assets/molduras/116.jpg", ancho: "2.5 cm", espesor: "1.5 cm" },
  { ref: "121", categoria: "Soluciones decorativas", imagen: "assets/molduras/121.jpg", ancho: "1.5 cm", espesor: "1.2 cm" },
  { ref: "308", categoria: "Soluciones decorativas", imagen: "assets/molduras/308.jpg", ancho: "3 cm", espesor: "1.5 cm" },
  { ref: "402 Cenefa", categoria: "Soluciones decorativas", imagen: "assets/molduras/402-cenefa.jpg", ancho: "10 cm", espesor: "2 cm" },
  { ref: "403", categoria: "Soluciones decorativas", imagen: "assets/molduras/403.jpg", ancho: "0.9 cm", espesor: "0.8 cm" },
  { ref: "405 Pasamanos", categoria: "Soluciones decorativas", imagen: "assets/molduras/405-pasamanos.jpg", ancho: "8 cm", espesor: "4 cm" },
  { ref: "514", categoria: "Soluciones decorativas", imagen: "assets/molduras/514.jpg", ancho: "3 cm", espesor: "1.2 cm" },
  { ref: "515", categoria: "Soluciones decorativas", imagen: "assets/molduras/515.jpg", ancho: "1 cm", espesor: "0.5 cm" },
  { ref: "516", categoria: "Soluciones decorativas", imagen: "assets/molduras/516.jpg", ancho: "2 cm", espesor: "1 cm" },
  { ref: "517", categoria: "Soluciones decorativas", imagen: "assets/molduras/517.jpg", ancho: "2.5 cm", espesor: "1.2 cm" },
  { ref: "7x3", categoria: "Soluciones decorativas", imagen: "assets/molduras/7x3.jpg", ancho: "7 cm", espesor: "3 cm" },
  { ref: "8x3", categoria: "Soluciones decorativas", imagen: "assets/molduras/8x3.jpg", ancho: "8 cm", espesor: "3 cm" },
  { ref: "8x4", categoria: "Soluciones decorativas", imagen: "assets/molduras/8x4.jpg", ancho: "8 cm", espesor: "4 cm" },
];

// Exponer categorías únicas (útil para futuros filtros)
const categorias = [...new Set(productos.map(p => p.categoria))];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { productos, categorias };
}